// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('SpareKart push is not configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'SpareKart push is not supported on this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVnHQwrJJtiKa0rbKgT-xLXy1Gz6pulFI',
    appId: '1:726470037175:android:7bf23347d088fcd4314732',
    messagingSenderId: '726470037175',
    projectId: 'sparekart-marketplace',
    storageBucket: 'sparekart-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnAIuRV07AUUFQ3aW-lyktqn8waQt6MFo',
    appId: '1:726470037175:ios:59c704cd1a105e8f314732',
    messagingSenderId: '726470037175',
    projectId: 'sparekart-marketplace',
    storageBucket: 'sparekart-marketplace.firebasestorage.app',
    iosBundleId: 'com.spare.kart',
  );

}